#!/usr/bin/env python3
"""Render a markdown meeting report to PDF.

Usage: md_to_pdf.py input.md output.pdf

Pure-Python pipeline (markdown2 -> xhtml2pdf) so it runs on both the
scraper server and the Mac that generates reports without system packages.
"""

import argparse
import sys
from pathlib import Path

import markdown2
from xhtml2pdf import pisa

CSS = """
@page {
    size: letter;
    margin: 2cm 1.8cm 2.2cm 1.8cm;
    @frame footer_frame {
        -pdf-frame-content: footer_content;
        bottom: 0.6cm; left: 1.8cm; width: 17cm; height: 0.8cm;
    }
}
body { font-family: Helvetica; font-size: 10.5pt; color: #1a1a1a; line-height: 1.45; }
h1 { font-size: 17pt; color: #0b3d62; border-bottom: 2px solid #0b3d62;
     padding-bottom: 6px; margin-bottom: 14px; }
h2 { font-size: 13pt; color: #0b3d62; margin-top: 18px; margin-bottom: 6px;
     border-bottom: 0.5px solid #b8c7d3; padding-bottom: 3px; }
h3 { font-size: 11pt; color: #333333; margin-top: 12px; margin-bottom: 4px; }
ul, ol { margin-top: 4px; margin-bottom: 8px; }
li { margin-bottom: 3px; }
table { border-collapse: collapse; margin: 8px 0; width: 100%; font-size: 9.5pt; }
th { background-color: #0b3d62; color: #ffffff; padding: 4px 6px; text-align: left; }
td { border-bottom: 0.5px solid #cccccc; padding: 4px 6px; }
code { font-family: Courier; font-size: 9pt; background-color: #f2f2f2; }
blockquote { margin-left: 12px; padding-left: 8px; border-left: 3px solid #b8c7d3;
             color: #444444; }
#footer_content { font-size: 8pt; color: #888888; text-align: center; }
"""

HTML_TEMPLATE = """<html>
<head><style>{css}</style></head>
<body>
{body}
<div id="footer_content">Generated by the Vancouver gov meeting minutes pipeline
 &mdash; page <pdf:pagenumber> of <pdf:pagecount></div>
</body>
</html>"""


def render(md_path: Path, pdf_path: Path) -> None:
    body = markdown2.markdown(
        md_path.read_text(encoding="utf-8"),
        extras=["tables", "fenced-code-blocks", "header-ids", "strike"],
    )
    html = HTML_TEMPLATE.format(css=CSS, body=body)
    with open(pdf_path, "wb") as fh:
        result = pisa.CreatePDF(html, dest=fh, encoding="utf-8")
    if result.err:
        raise RuntimeError(f"xhtml2pdf reported {result.err} error(s)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=Path, help="markdown report to render")
    parser.add_argument("output", type=Path, help="destination PDF path")
    args = parser.parse_args()
    if not args.input.is_file():
        print(f"error: {args.input} not found", file=sys.stderr)
        return 1
    try:
        render(args.input, args.output)
    except Exception as exc:  # noqa: BLE001 - CLI boundary
        if args.output.exists():
            args.output.unlink()
        print(f"error: failed to render {args.input}: {exc}", file=sys.stderr)
        return 1
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
